movie/card/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from card import views
app_name="card"


urlpatterns = [

    # path('',views.home,name="home"),
    path('',views.MovieList.as_view(),name="home"),

    # path('addmovie',views.addmovie,name="addmovie"),
    path('addmovie',views.Movieadd.as_view(),name="addmovie"),

    # path('viewmovies/<int:p>',views.viewmovies,name="viewmovies"),
    path('viewmovies/<int:pk>',views.MovieDetail.as_view(),name="viewmovies"),


    # path('moviedelete/<int:p>', views.moviedelete, name="moviedelete"),
    path('moviedelete/<int:pk>', views.Moviedelete.as_view(), name="moviedelete"),


    # path('movieupdate/<int:p>', views.movieupdate, name="movieupdate"),
    path('movieupdate/<int:pk>', views.Movieupdate.as_view(), name="movieupdate"),

]

movie/movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('card.urls')),


]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/card/models.py
from django.db import models

# Create your models here.

class Cards(models.Model):
    title=models.CharField(max_length=20)
    desc=models.CharField(max_length=500)
    year=models.IntegerField()
    image=models.ImageField(upload_to="card/image",null=True,blank=True)

    def __str__(self):
        return self.title

movie/card/forms.py
from django import forms
from card.models import Cards


class Cardsform(forms.ModelForm):

    class Meta:
        model=Cards
        fields="__all__"

movie/card/views.py
from django.shortcuts import render

from card.models import Cards

from card.forms import Cardsform
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views here.


# def home(request):
#     k = Cards.objects.all()
#     return render(request,'home.html',{'b': k})

class MovieList(ListView):     #ListView displays all objects/records retrieving from a model.
    model=Cards
    template_name="home.html"
    context_object_name="b"




# def addmovie(request):
#     if(request.method=="POST"):
#         t=request.POST['t']
#         d=request.POST['d']
#         y=request.POST['y']
#         i=request.FILES['i']
#         b=Cards.objects.create(title=t,desc=d,year=y,image=i)
#         b.save()
#         return home(request)
#
#     return render(request,'addmovie.html')


class Movieadd(CreateView):   #createview displays a form adding new object and handles form submission
    model=Cards
    template_name="addmovie.html"
    fields='__all__'
    success_url=reverse_lazy("card:home")




# def viewmovies(request,p):
#         b=Cards.objects.get(id=p)
#         return render(request, 'viewmovies.html', {'b': b})

class MovieDetail(DetailView):
    model=Cards
    template_name="viewmovies.html"
    context_object_name="b"



# def moviedelete(request,p):
#     b =Cards.objects.get(id=p)
#     b.delete()
#     return home(request)

class Moviedelete(DeleteView):
    model = Cards
    template_name = "delete.html"
    success_url = reverse_lazy('card:home')



# def movieupdate(request,p):
#     b=Cards.objects.get(id=p)
#     if (request.method == "POST"):  #After submission
#         form=Cardsform(request.POST,request.FILES,instance=b)  #Creates form object initialized with values inside request.POST
#         if form.is_valid():
#             form.save()  # save the form object inside DB table
#         return home(request)
#
#     form=Cardsform(instance=b)
#     return render(request,"update.html",{"form":form})



class Movieupdate(UpdateView):
    model=Cards
    template_name ="update.html"
    fields='__all__'
    success_url=reverse_lazy('card:home')

movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!--<center>-->
<!--    <h2>ADD MOVIE DETAILS</h2>-->
<!--   <form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--      <div class="mb-3">-->
<!--        <label  class="form-label">Title</label>-->
<!--        <input type="text" class="form-control" name="t" placeholder="Enter the Movie title">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">Description</label>-->
<!--        <input type="text" class="form-control" name="d" placeholder="Enter the Description">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">year</label>-->
<!--        <input type="text" class="form-control" name="y" placeholder="Enter the year">-->
<!--      </div>-->
<!--  <div class="mb-3">-->
<!--        <label class="form-label">Image</label>-->
<!--        <input type="file" class="form-control" name="i" placeholder="choose a file">-->
<!--      </div>-->
<!--      <div>-->
<!--          <input type="submit" class="form-control">-->
<!--      </div>-->
<!--    </div></form>-->
<!--</center>-->


    <h2>ADD MOVIE DETAILS</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

        {{form|crispy}}

    <input type="submit">
</form>

{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Store</a>
    <form class="d-flex">

      <a href="{% url 'card:addmovie' %}" class="btn btn-success">Add Movie</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}


<form method="POST">
        {% csrf_token %}
        <p>Are You sure you want to delete??</p>
        <input type="submit">
</form>


{% endblock %}

movie/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h2>Welcome to Movie Details</h2>
</center>
{% for i in b %}

<div class="card" style="display: inline-block; width:18rem;">
  <img src="{{i.image.url}}" height="100px" width="100px">
  <div class="card-body">
    <h5 class="card-title">{{i.title }}</h5>
    <p class="card-text" style="height:320px;">{{i.desc }}</p>
    <a href="{% url 'card:viewmovies' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

{% endfor %}

{% endblock %}

movie/templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <h3 class="mt-4"></h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{form.as_table}}
            </table>
        <input type="submit">
    </form>
</center>

{% endblock %}

movie/templates/viewmovies.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="comtainer">
    <div class="row">
        <div class="col-md-6">
            <img src="{{b.image.url}}" width="300" height="350">
        </div>
<div class="col-md-6">
    <h4>{{b.title}}</h4>
    <h6>{{b.desc}}</h6>
    <h6>{{b.year}}</h6>


    <a href="{% url 'card:movieupdate' b.id %}" class="btn btn-danger">UPDATE</a>
    <a href="{% url 'card:moviedelete' b.id %}" class="btn btn-danger">Delete</a>
</div>
    </div>
</div>

{% endblock %}